version: '3'

services:
        webserver:
                build: .docker/nginx
                ports:
                        - "780:80"
                volumes:
                        - .:/var/www

        app:
                build: . 

        database:
                image: mysql:5.7
                environment:
                        - MYSQL_RANDOM_ROOT_PASSWORD=yes
                        - MYSQL_USER=app
                        - MYSQL_PASSWORD=123456
                        - MYSQL_DATABASE=laravel
