version: '3'

services:
        webserver:
                build: .docker/nginx
                ports:
                        - "780:80"
                volumes:
                        - .:/var/www
                environment:
                        - php_host=app
                        - php_port=9000

        app:
                build: . 
                environment:
                        - CACHE_DRIVER=redis

        database:
                image: mysql:5.7
                environment:
                        - MYSQL_RANDOM_ROOT_PASSWORD=yes
                        - MYSQL_USER=app
                        - MYSQL_PASSWORD=123456
                        - MYSQL_DATABASE=laravel

        cache:
                image: redis:5.0-alpine
