version: '3'

services:
        webserver:
                build: .docker/nginx
                ports:
                        - "780:80"
                volumes:
                        - .:/var/www

        app:
                build: . 
                volumes:
                        - .:/var/www


